name: Testes Amazon

on:
  workflow_dispatch:  # Permite a execução manual do workflow

jobs:
  rodar_testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar dependências
        run: npm install

      - name: Rodar testes de Amazon
        run: npx cypress run --spec "cypress/e2e/features/compra.Amazon/amazon.feature"
        env:
          CYPRESS_baseUrl: https://www.amazon.com.br
