name: Testes Amazon

on:
  schedule:
    - cron: '0 17 * * *' # Executa todos os dias às 8:00 AM
  workflow_dispatch:

jobs:
  rodar_testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar dependências
        run: npm install

      - name: Rodar testes de Amazon
        run: npx cypress run --spec "cypress/e2e/features/compra.Amazon/amazon.feature"
        env:
          CYPRESS_baseUrl: https://www.amazon.com.br